---
image: python:3.8
# before_script:
#   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#   - pip install docker-auto-labels

stages:
  - build
  - test
  - deploy

before_script:
  - pip3 install pipenv
  - docker info

# https://github.com/fcfangcc/pylint-pydantic/issues/3
lint:
  stage: build
  script:
    - pipenv install --dev
    - pipenv run black --check ./main.py ./cogs
    - pipenv run pylint --fail-under 9.0 ./main.py ./cogs
  except:
    - main

unit:
  stage: test
  script:
    - cat $ENV_FILE > .env
    - pipenv install --dev
    - pipenv run coverage run --source=. -m pytest tests/unit
    - pipenv run coverage report -m
  except:
    - main

build_image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/conceptual-coop/internal-projects/jonk .
    - docker push registry.gitlab.com/conceptual-coop/internal-projects/jonk
  only:
    - main
